Features media queries
omou-org/omou-org.github.io pull request #12
Opened 2020-04-21 21:42 UTC by clam1987

#10 Still working on this but I have most of the issues fixed.

2020-04-23 02:48 UTC, dhuangg requested changes

2020-04-23 02:48 UTC, dhuangg commented on src/components/FeaturesCard/FeaturesCard.js
> +          props.title == "Standardized Registration and Payments"
This was a jank way to do it, honestly would recommend giving each section object a style attribute so we can just do something like: 
`style={ props.style }`

2020-04-23 02:48 UTC, dhuangg commented on src/components/FeaturesCard/FeaturesCard.js
> +          props.title == "Standardized Registration and Payments"
*I originally implemented this fix lol. don't think i'm getting mad at your code or anything

2020-05-13 01:06 UTC, CalvinFronda commented on src/components/FeaturesCard/FeaturesCard.js
> +  console.log(props)
remove console.log

2020-05-20 02:39 UTC, merged